[package]
name = "teamsearch_utils"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
path-absolutize = { workspace = true}
log = { workspace = true }
once_cell = { workspace = true }
clap = { workspace = true }
