cargo-features = ["edition2024"]

[package]
name = "teamsearch_utils"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
clap = { workspace = true }
